import json, os, sys, re, subprocess
sys.path.insert(0, os.path.dirname(__file__)); from art import svg
# 使い方: python3 tools/mihon/make_samples.py [~/src/liftoff-hp] [cafe,school,...]
# 見本帳の「業種の見本」（架空のお店）を make_site.py で作り直す。設定は samples/<名前>/site.json に置かれる
import tempfile
HERE=os.path.dirname(os.path.abspath(__file__))
ROOT=os.path.expanduser(sys.argv[1]) if len(sys.argv)>1 else os.path.dirname(os.path.dirname(HERE))
S=tempfile.mkdtemp()
COMMON=dict(area='〇〇県〇〇市', tel='0000-00-0000', line_url='#reserve', address='〒000-0000 〇〇県〇〇市〇〇町1-2-3',
            line_msg='ホームページを見ました。{name}について相談したいです。', info_eyebrow='about')
def menu(id,name,text,price=None,note=None,items=None,icon=None):
    m=dict(id=id,name=name,text=text,image=f'images/menu-{id}.svg',w=1000,h=750,alt=name+'の写真',_icon=icon)
    if price: m['price']=price
    if note: m['price_note']=note
    if items: m['items']=items
    return m
SAMPLES={
'cafe':dict(c=dict(slug='komorebi',name='喫茶 こもれび',short_name='こもれび',kind='喫茶・軽食｜〇〇市',
  catch_html='<span class="nw">朝のコーヒーから、</span><br><span class="nw">昼のひと休みまで。</span>',
  lead='〇〇市の小さな喫茶店です。モーニング・日替わりランチ・自家製のケーキをご用意しています。',
  title_place='〇〇市の喫茶店',description='〇〇市の喫茶店「こもれび」のホームページです（デザイン見本・架空のお店）。',
  theme_base='salon',theme=dict(primary='#b5683b',primary_deep='#97522b',accent='#d6a35c',accent_soft='#ead2a8',pale='#f6ebdf',dark='#2e2620',dark2='#3a3029',bg='#f8f3ec',bg2='#efe6da',ink='#3a302a',muted='#7a6b5f',line='#e5d8c8'),
  mark='leaf',font='mincho',menu_title='メニュー',menu_word='メニュー',menu_lead='料金は見本です。',
  menu_note='季節によって内容が変わります。くわしくはお問い合わせください。',
  menus=[menu('morning','モーニング','トースト・ゆで卵・サラダに、お好きな飲みものを。','550円','飲みもの代＋',icon=['toast']),
         menu('lunch','日替わりランチ','週ごとに変わる、ごはんとおかずの定食です。','900円',icon=['cup','toast']),
         menu('coffee','コーヒー','注文を受けてから一杯ずつ淹れています。','450円',icon=['beans']),
         menu('cake','ケーキ','店で焼いたケーキを、日によって2〜3種類。','400円',icon=['cake'])],
  hours='8:00〜17:00（見本）',holiday='水曜日（見本）',parking='3台（見本）',payment='現金・QRコード決済（見本）',
  reserve_title='ご予約・お問い合わせ',info_title='お店のこと',reserve_lead='貸し切りや、ケーキのお取り置きもご相談ください。',
  faq=[dict(q='予約はできますか？',a='ランチのみ、前日までにお電話でお受けしています（見本）。'),
       dict(q='子ども連れでも大丈夫ですか？',a='はい。子ども用のいすをご用意しています（見本）。'),
       dict(q='ケーキの持ち帰りはできますか？',a='はい、できます。数に限りがあるので、お取り置きはお電話でどうぞ（見本）。')],
  schema_type='CafeOrCoffeeShop',area_served='〇〇市'),
  hero=['cup','cake','beans'], c1='#efe2d2', c2='#dcc7ad', stroke='#8a5a38', ink='#8a6a50', bg='#f1e7da'),
'school':dict(c=dict(slug='hidamari',name='こども英語教室 ひだまり',short_name='ひだまり英語',kind='こども英語教室｜〇〇市',
  catch_html='<span class="nw">「話してみたい」を、</span><br><span class="nw">いっしょに育てます。</span>',
  lead='〇〇市の、少人数のこども英語教室です。歌やゲームから始めて、読む・書くまで少しずつ。',
  title_place='〇〇市のこども英語教室',description='〇〇市のこども英語教室「ひだまり」のホームページです（デザイン見本・架空の教室）。',
  theme_base='fresh',theme=dict(primary='#2f7fd1',primary_deep='#2166ae',accent='#f2b84b',accent_soft='#f7d99a',pale='#e8f1fb',dark='#1f3550',dark2='#2a4566',bg='#f7fafd',bg2='#eaf1f9',ink='#22303e',muted='#5d6b7a',line='#d6e2ee'),
  mark='dot',font='gothic',menu_title='クラスと月謝',menu_word='クラス',menu_lead='月謝は見本です。',
  menu_note='入会金・教材費はお問い合わせください。',
  menus=[menu('kids','幼児クラス','3〜6才。歌・絵本・ゲームで英語に親しみます。','月 6,000円','週1回',icon=['music']),
         menu('elementary','小学生クラス','聞く・話すに加えて、読む・書くも少しずつ。','月 7,000円','週1回',icon=['abc']),
         menu('junior','中学生クラス','学校の授業に合わせて、文法と会話をくり返します。','月 8,000円','週1回',icon=['book']),
         menu('trial','体験レッスン','まずは一度、教室の雰囲気を見に来てください。','無料',icon=['star'])],
  flow_title='入会までの流れ',flow=[dict(title='お問い合わせ',text='LINEかお電話で、体験の日を決めます。'),dict(title='体験レッスン',text='実際のレッスンに参加していただきます。'),dict(title='ご入会',text='クラスと曜日を決めて、始めます。')],
  hours='平日 15:00〜20:00（見本）',holiday='土・日・祝日（見本）',parking='2台（見本）',
  reserve_title='体験・お問い合わせ',info_title='教室のこと',reserve_lead='体験レッスンは、保護者の方も一緒に見学できます。',
  faq=[dict(q='英語がはじめてでも大丈夫ですか？',a='はい。はじめての子がほとんどです。'),dict(q='振替はできますか？',a='同じ月の中で、ほかのクラスに振り替えられます（見本）。'),dict(q='送り迎えの駐車場はありますか？',a='教室の前に2台分あります（見本）。')],
  schema_type='EducationalOrganization',area_served='〇〇市'),
  hero=['abc','book','pencil'], c1='#e6f0fb', c2='#cfe0f3', stroke='#2f6fb5', ink='#4a6a8f', bg='#e9f0f8'),
'reform':dict(c=dict(slug='morino',name='森野工務店',short_name='森野工務店',kind='工務店・リフォーム｜〇〇市',
  catch_html='<span class="nw">水まわりから屋根まで、</span><br><span class="nw">家のことを近くで。</span>',
  lead='〇〇市の工務店です。リフォーム・修理・小さな困りごとまで、下見をしてからお見積もりします。',
  title_place='〇〇市の工務店・リフォーム',description='〇〇市の工務店「森野工務店」のホームページです（デザイン見本・架空のお店）。',
  theme_base='fresh',theme=dict(primary='#c0662b',primary_deep='#a25422',accent='#2b5d8a',accent_soft='#c9d6e3',pale='#f4ece4',dark='#1d2a36',dark2='#283846',bg='#f6f4f0',bg2='#ece8e1',ink='#23282e',muted='#646a70',line='#dcd6cc'),
  mark='dot',font='gothic',menu_title='お仕事の内容',menu_word='仕事',menu_lead='小さな修理からお受けしています。',
  menu_note='料金は家の状態で変わります。下見のうえでお見積もりをお出しします。',
  menus=[menu('mizu','水まわり','台所・お風呂・トイレ・洗面所の取りかえや修理。',icon=['faucet']),
         menu('yane','外壁・屋根','ぬりかえ・雨もりの修理・とい の取りかえ。',icon=['roof']),
         menu('naisou','内装','壁紙・床・建具・手すりの取りつけなど。',icon=['house']),
         menu('shuuri','小さな修理','戸のたてつけ・網戸の張りかえなど、1か所からどうぞ。',icon=['tools'])],
  flow_title='ご依頼の流れ',flow=[dict(title='ご相談',text='困っていることをお知らせください。'),dict(title='下見',text='おうちに伺って、様子を見せていただきます。'),dict(title='お見積もり',text='内容と金額をお出しします。決めるのはそのあとで。'),dict(title='工事',text='日程を決めて工事します。終わったら一緒に確かめます。')],
  hours='8:00〜18:00（見本）',holiday='日曜日（見本）',service_area='〇〇市とその周辺（見本）',
  reserve_title='ご相談・お見積もり',info_title='森野工務店について',reserve_lead='下見とお見積もりは無料です（見本）。',
  faq=[dict(q='1か所だけの修理でも頼めますか？',a='はい、お受けしています。'),dict(q='見積もりのあとで断ってもいいですか？',a='はい、大丈夫です（見本）。'),dict(q='どこまで来てもらえますか？',a='〇〇市とその周辺でお受けしています（見本）。')],
  schema_type='HomeAndConstructionBusiness',area_served='〇〇市'),
  hero=['house','faucet','tools'], c1='#efe9e1', c2='#ddd3c6', stroke='#2b5d8a', ink='#5d6670', bg='#ebe6de'),
'hair':dict(c=dict(slug='nagi',name='hair salon nagi',short_name='nagi',kind='美容室｜〇〇市',
  catch_html='<span class="nw">いつもの髪を、</span><br><span class="nw">少しだけ新しく。</span>',
  lead='〇〇市の、席が2つだけの美容室です。ひとりのスタイリストが、最初から最後まで担当します。',
  title_place='〇〇市の美容室',description='〇〇市の美容室「nagi」のホームページです（デザイン見本・架空のお店）。',
  theme_base='salon',theme=dict(primary='#8c7b6b',primary_deep='#6f6052',accent='#c9a27e',accent_soft='#e3d1bd',pale='#f1ece6',dark='#232120',dark2='#302d2b',bg='#f5f3f0',bg2='#ebe7e2',ink='#2a2826',muted='#6e6862',line='#ddd6ce'),
  mark='dot',font='mincho',menu_title='メニュー・料金',menu_word='メニュー',menu_lead='料金は見本です。',
  menu_note='髪の長さや量で変わることがあります。',
  menus=[menu('cut','カット','顔まわりのくせや、ふだんの手入れをうかがってから切ります。','4,400円',icon=['scissors']),
         menu('color','カラー','明るさ・色味を相談しながら決めます。','6,600円〜',icon=['bottle']),
         menu('perm','パーマ','ゆるいくせづけから、しっかりしたカールまで。','8,800円〜',icon=['comb']),
         menu('spa','ヘッドスパ','頭皮をていねいに洗い、ゆっくり過ごしていただく時間です。','3,300円',icon=['dryer'])],
  hours='10:00〜19:00（見本）',holiday='月曜日（見本）',parking='2台（見本）',payment='現金・クレジットカード（見本）',
  reserve_title='ご予約',info_title='お店のこと',reserve_lead='ご予約はLINEかお電話でどうぞ。',
  faq=[dict(q='はじめてでも予約できますか？',a='はい。はじめての方も、LINEかお電話でどうぞ。'),dict(q='子どもも切ってもらえますか？',a='はい。小学生から承っています（見本）。'),dict(q='当日の予約はできますか？',a='空いていればお受けします。お電話でお問い合わせください。')],
  schema_type='HairSalon',area_served='〇〇市'),
  hero=['scissors','comb','bottle'], c1='#efebe6', c2='#ddd5cc', stroke='#6f6052', ink='#7a7067', bg='#ece8e3'),
'relax':dict(c=dict(slug='yururi',name='整体 ゆるり',short_name='ゆるり',kind='整体｜〇〇市',
  catch_html='<span class="nw">からだの話を、</span><br><span class="nw">ゆっくり聞くところから。</span>',
  lead='〇〇市の整体院です。いまのからだの状態をうかがってから、ひとりひとりに合わせて施術します。',
  title_place='〇〇市の整体',description='〇〇市の整体「ゆるり」のホームページです（デザイン見本・架空のお店）。',
  theme_base='fresh',theme=dict(primary='#4f8f86',primary_deep='#3d756d',accent='#d9b26a',accent_soft='#ecd9ad',pale='#e7f1ef',dark='#22393a',dark2='#2d4848',bg='#f5f8f7',bg2='#e8efed',ink='#26302f',muted='#5f6d6b',line='#d4e0dd'),
  mark='leaf',font='mincho',menu_title='メニュー・料金',menu_word='メニュー',menu_lead='料金は見本です。',
  menu_note='どれにすればいいか迷うときは、お気軽にご相談ください。',
  menus=[menu('basic','整体 60分','お話をうかがってから、全身をていねいに施術します。','5,500円',icon=['hands']),
         menu('short','整体 30分','時間のないときに、気になるところを中心に。','3,300円',icon=['leaf']),
         menu('first','はじめての方','最初にお話をうかがう時間を長めにとります。','+1,100円',icon=['chair']),
         menu('ticket','回数券','5回分をまとめてお求めいただけます。','25,000円',icon=['ticket'])],
  hours='9:00〜19:00（見本）',holiday='木曜日（見本）',parking='3台（見本）',payment='現金・QRコード決済（見本）',
  reserve_title='ご予約',info_title='お店のこと',reserve_lead='ご予約はLINEかお電話でどうぞ。持病のある方・妊娠中の方は、事前にご相談ください。',
  faq=[dict(q='はじめてでも大丈夫ですか？',a='はい。最初にお話をうかがう時間をとっています。'),dict(q='着がえは必要ですか？',a='お着がえをご用意しています（見本）。'),dict(q='当日の予約はできますか？',a='空いていればお受けします。お電話でお問い合わせください。')],
  schema_type='HealthAndBeautyBusiness',area_served='〇〇市'),
  hero=['leaf','hands','cal'], c1='#e6efed', c2='#cfdfdb', stroke='#3d756d', ink='#5c7470', bg='#e7eeec'),
# ---- 2026/10/9 追加の10業種（どれも架空のお店。「作業の前・後」の部品は整備・設備だけ。合計の目安（calc）は入れない：決定事項） ----
'izakaya':dict(c=dict(slug='konara',name='居酒屋 こなら',short_name='こなら',kind='居酒屋・和食｜〇〇市',
  catch_html='<span class="nw">今日の魚と、</span><br><span class="nw">あたたかいごはん。</span>',
  lead='〇〇市の小さな居酒屋です。市場で仕入れた魚と、季節の野菜の煮物・焼きもの。ひとりでも、家族でも。',
  title_place='〇〇市の居酒屋・和食',description='〇〇市の居酒屋「こなら」のホームページです（デザイン見本・架空のお店）。',
  theme_base='wa',theme=dict(primary='#b8432e',primary_deep='#96351f',accent='#c9a85b',accent_soft='#e4d3a3',pale='#f3ebdd',dark='#1f2430',dark2='#2b3140',bg='#f6f2ea',bg2='#ece6d8',ink='#26241f',muted='#6c675c',line='#d8d0bf'),
  mark='dot',font='mincho',menu_title='お品書き',menu_word='料理',menu_lead='料金は見本です。',
  menu_note='仕入れによって内容が変わります。苦手なものがあれば、ご予約のときにお知らせください。',
  menus=[menu('course','おまかせコース','前菜・刺身・焼きもの・ごはん・甘味。2名さまから。','4,400円','お一人',icon=['fish','sake']),
         menu('sashimi','旬の刺身 盛り合わせ','その日の魚を3〜5種。','1,650円',icon=['fish']),
         menu('yaki','炭火の焼きもの','鶏・豚・野菜の串を1本から。','330円〜','1本',icon=['grill']),
         menu('drink','飲みもの','地元の日本酒・生ビール・ソフトドリンク。','550円〜',icon=['beer','sake'])],
  hours='17:00〜23:00（見本）',holiday='月曜日（見本）',parking='3台（見本）',payment='現金・QRコード決済（見本）',
  reserve_title='ご予約',info_title='お店のこと',reserve_lead='席のご予約・宴会のご相談は、LINEかお電話でどうぞ。',
  faq=[dict(q='予約なしでも入れますか？',a='はい。席が空いていればご案内します。週末は予約をおすすめします（見本）。'),
       dict(q='宴会は何人までできますか？',a='座敷で12名さままで（見本）。貸し切りはご相談ください。'),
       dict(q='子ども連れでも大丈夫ですか？',a='はい。座敷と子ども用の食器をご用意しています（見本）。')],
  schema_type='Restaurant',area_served='〇〇市'),
  hero=['sake','fish','grill'], c1='#efe6d6', c2='#dccdb3', stroke='#96351f', ink='#7a6a55', bg='#ede7da'),
'bakery':dict(c=dict(slug='kotori',name='ベーカリー ことり',short_name='ことり',kind='パン・焼き菓子｜〇〇市',
  catch_html='<span class="nw">朝いちばんに焼いた</span><br><span class="nw">パンと焼き菓子。</span>',
  lead='〇〇市の小さなパン屋です。食パン・惣菜パン・焼き菓子を、毎朝お店で焼いています。',
  title_place='〇〇市のパン屋・洋菓子',description='〇〇市のパン屋「ことり」のホームページです（デザイン見本・架空のお店）。',
  theme_base='salon',theme=dict(primary='#c98a3a',primary_deep='#a86f2a',accent='#7a9a5a',accent_soft='#d9e2c3',pale='#f9efe0',dark='#3b2e24',dark2='#4a3b2f',bg='#fbf7f0',bg2='#f2ebdf',ink='#3a3129',muted='#7a6e62',line='#e6dccb'),
  mark='dot',font='gothic',menu_title='パンと焼き菓子',menu_word='商品',menu_lead='料金は見本です。',
  menu_note='日によって並ぶものが変わります。売り切れのときはごめんなさい。',
  menus=[menu('shoku','食パン','毎日食べても飽きない、やわらかい食パン。','380円','1斤',icon=['bread']),
         menu('souzai','惣菜パン','カレーパン・ウインナーロールなど、日替わりで。','200円〜',icon=['croissant']),
         menu('yaki','焼き菓子','クッキー・マフィン・スコーン。贈りものにも。','180円〜',icon=['cookie']),
         menu('cake','お祝いのケーキ','誕生日や記念日に。3日前までにご予約ください。','3,200円〜','予約制',icon=['cake'])],
  hours='8:00〜売り切れまで（見本）',holiday='火・水曜日（見本）',parking='4台（見本）',payment='現金・QRコード決済（見本）',
  reserve_title='ご予約・お問い合わせ',info_title='お店のこと',reserve_lead='ケーキのご予約・パンのお取り置きは、LINEかお電話でどうぞ。',
  faq=[dict(q='何時ごろ品がそろいますか？',a='9時ごろにひととおり並びます（見本）。'),
       dict(q='取り置きはできますか？',a='はい。前日までにLINEかお電話でお知らせください（見本）。'),
       dict(q='アレルギーの表示はありますか？',a='主な材料は店頭の札に書いています。気になるものは、お気軽にお尋ねください。')],
  schema_type='Bakery',area_served='〇〇市'),
  hero=['bread','croissant','cookie'], c1='#f3e8d6', c2='#e3d1b4', stroke='#a86f2a', ink='#8a7355', bg='#f1e8da'),
'nail':dict(c=dict(slug='tsumugi',name='nail & eyelash tsumugi',short_name='tsumugi',kind='ネイル・まつげ｜〇〇市',
  catch_html='<span class="nw">指先とまつげに、</span><br><span class="nw">ちょうどいい彩りを。</span>',
  lead='〇〇市の、席がひとつだけのネイル・まつげサロンです。ご希望をうかがってから、ひとつずつ仕上げます。',
  title_place='〇〇市のネイル・まつげサロン',description='〇〇市のネイル・まつげサロン「tsumugi」のホームページです（デザイン見本・架空のお店）。',
  theme_base='salon',theme=dict(primary='#c47a8a',primary_deep='#a55f70',accent='#b9a07a',accent_soft='#e1d4bd',pale='#f8eef0',dark='#2d2628',dark2='#3a3133',bg='#faf6f5',bg2='#f1e9e8',ink='#332c2e',muted='#75696c',line='#e5d9da'),
  mark='heart',font='mincho',menu_title='メニュー・料金',menu_word='メニュー',menu_lead='料金は見本です。',
  menu_note='デザインや本数で変わることがあります。',
  menus=[menu('gel','ジェルネイル','色・デザインを相談しながら決めます。','5,500円〜',icon=['nail']),
         menu('off','つけかえ・オフ','ほかのお店でつけたものも、お受けしています。','1,100円',icon=['sparkle']),
         menu('ext','まつげエクステ','目の形に合わせて、1本ずつつけていきます。','4,400円〜','80本',icon=['lash']),
         menu('perm','まつげパーマ','自分のまつげを、上向きに整えます。','4,400円',icon=['lash','sparkle'])],
  hours='10:00〜19:00（見本）',holiday='水曜日（見本）',parking='1台（見本）',payment='現金・クレジットカード（見本）',
  reserve_title='ご予約',info_title='お店のこと',reserve_lead='ご予約はLINEかお電話でどうぞ。目の病気や治療中の方は、事前にご相談ください。',
  faq=[dict(q='はじめてでも予約できますか？',a='はい。はじめての方も、LINEかお電話でどうぞ。'),dict(q='デザインの持ち込みはできますか？',a='はい。写真を見せていただければ、近い形でお作りします。'),dict(q='どのくらい時間がかかりますか？',a='ジェルネイルで1時間半〜2時間ほどです（見本）。')],
  schema_type='BeautySalon',area_served='〇〇市'),
  hero=['nail','lash','sparkle'], c1='#f3e6e8', c2='#e4cfd3', stroke='#a55f70', ink='#8a6f75', bg='#f1e6e7'),
'juku':dict(c=dict(slug='tsubasa',name='つばさ学習教室',short_name='つばさ学習教室',kind='学習塾｜〇〇市',
  catch_html='<span class="nw">「わかった」を、</span><br><span class="nw">ひとつずつ増やす。</span>',
  lead='〇〇市の、少人数の学習塾です。学校の授業に合わせて、つまずいたところまで戻ってやり直します。',
  title_place='〇〇市の学習塾',description='〇〇市の学習塾「つばさ学習教室」のホームページです（デザイン見本・架空の教室）。',
  theme_base='fresh',theme=dict(primary='#2f6fb5',primary_deep='#24588f',accent='#e9a23b',accent_soft='#f5d7a3',pale='#e9f0f9',dark='#1b2b40',dark2='#263a52',bg='#f7f9fc',bg2='#eaf0f6',ink='#22303e',muted='#5f6b78',line='#d5dfe9'),
  mark='dot',font='gothic',menu_title='コースと月謝',menu_word='コース',menu_lead='月謝は見本です。',
  menu_note='入会金・教材費はお問い合わせください。',
  menus=[menu('sho','小学生コース','算数・国語を中心に、学校の進みに合わせて。','月 8,800円','週2回',icon=['pencil']),
         menu('chu','中学生コース','5教科。定期テストの前は回数を増やします。','月 13,200円','週2回',icon=['book']),
         menu('kou','高校生コース','教科を選んで、自分のペースで進めます。','月 16,500円','週2回',icon=['graph']),
         menu('trial','体験授業','まずは2回、教室の様子を見に来てください。','無料','2回まで',icon=['star'])],
  flow_title='入塾までの流れ',flow=[dict(title='お問い合わせ',text='LINEかお電話で、面談の日を決めます。'),dict(title='面談',text='いまの様子と、目標をうかがいます。'),dict(title='体験授業',text='実際の授業に参加していただきます。'),dict(title='ご入塾',text='コースと曜日を決めて、始めます。')],
  hours='平日 15:00〜21:30・土 13:00〜19:00（見本）',holiday='日曜・祝日（見本）',parking='3台（見本）',
  reserve_title='体験・お問い合わせ',info_title='教室のこと',reserve_lead='体験授業は無料です。保護者の方の見学もできます。',
  faq=[dict(q='自習室は使えますか？',a='はい。開いている時間はいつでも使えます（見本）。'),dict(q='部活と両立できますか？',a='曜日と時間を相談して決めます。'),dict(q='月の途中からでも入れますか？',a='はい。月謝は日割りでお受けしています（見本）。')],
  schema_type='EducationalOrganization',area_served='〇〇市'),
  hero=['book','pencil','graph'], c1='#e6eef8', c2='#cfdcef', stroke='#24588f', ink='#4e6688', bg='#e8eef6'),
'car':dict(c=dict(slug='hoshino',name='ほしの自動車整備',short_name='ほしの自動車',kind='自動車の整備・板金｜〇〇市',
  catch_html='<span class="nw">車検から板金まで、</span><br><span class="nw">まちの車の相談所。</span>',
  lead='〇〇市の自動車整備工場です。車検・点検・修理・板金塗装を、どのメーカーの車でもお受けしています。',
  title_place='〇〇市の自動車整備・板金',description='〇〇市の自動車整備工場「ほしの自動車整備」のホームページです（デザイン見本・架空のお店）。',
  theme_base='fresh',theme=dict(primary='#d9742b',primary_deep='#b65d1e',accent='#3b6ea5',accent_soft='#c7d7ea',pale='#f6ede3',dark='#1e2328',dark2='#2a3139',bg='#f5f4f1',bg2='#eae8e3',ink='#23262a',muted='#636870',line='#d9d6cf'),
  mark='dot',font='gothic',menu_title='お仕事の内容',menu_word='仕事',menu_lead='料金は見本です。',
  menu_note='車種と状態で変わります。見せていただいてからお見積もりをお出しします。',
  menus=[menu('shaken','車検','法定費用込みの目安です。代車もご用意しています。','49,500円〜','軽自動車',icon=['car']),
         menu('oil','点検・オイル交換','待っている間にできる、ふだんの点検。','4,400円〜',icon=['wrench']),
         menu('bankin','板金・塗装','へこみ・すり傷の修理。保険を使う修理もご相談ください。',icon=['spray']),
         menu('tire','タイヤ交換・保管','夏タイヤ・冬タイヤの交換と、お預かり。','2,200円〜','4本',icon=['tire'])],
  flow_title='ご依頼の流れ',flow=[dict(title='ご相談',text='車の様子と、気になることをお知らせください。'),dict(title='お預かり・お見積もり',text='車を見せていただき、内容と金額をお出しします。'),dict(title='作業',text='決めていただいてから作業します。'),dict(title='お引き渡し',text='作業した所を一緒に確かめて、お渡しします。')],
  parts=dict(cases=dict(title='修理の例',eyebrow='works',lead='修理の前と後を、並べてご覧いただけます。',label_before='修理前',label_after='修理後',
                        items=[dict(before=dict(image='images/case1-before.svg',alt='修理前のドア（見本）',_icon=['car']),after=dict(image='images/case1-after.svg',alt='修理後のドア（見本）',_icon=['car','sparkle']),title='ドアのへこみの修理',meta='軽自動車　板金・塗装',text='駐車場でぶつけたへこみを、板金で戻してから塗装しました。'),
                               dict(before=dict(image='images/case2-before.svg',alt='修理前のバンパー（見本）',_icon=['spray']),after=dict(image='images/case2-after.svg',alt='修理後のバンパー（見本）',_icon=['spray','sparkle']),title='バンパーのすり傷',meta='普通車　塗装',text='傷の部分だけを削って、まわりの色に合わせて塗りました。')]),
             compare=dict(title='修理の前と後',lead='つまみを動かすと、同じ場所の前と後が見比べられます。',label_before='修理前',label_after='修理後',caption='ドアのへこみの修理（見本）')),
  hours='9:00〜18:00（見本）',holiday='日曜・祝日（見本）',parking='5台（見本）',payment='現金・クレジットカード（見本）',
  info_extra=[['代車','ご用意しています（要予約・見本）']],
  reserve_title='ご相談・お見積もり',info_title='ほしの自動車整備について',reserve_lead='お見積もりは無料です（見本）。写真を送っていただければ、おおよその目安もお伝えします。',
  faq=[dict(q='車検はいつごろ頼めばいいですか？',a='有効期限の1か月前から受けられます。早めにご相談ください。'),dict(q='代車はありますか？',a='はい。台数に限りがあるので、ご予約のときにお知らせください（見本）。'),dict(q='保険を使う修理もできますか？',a='はい。保険会社とのやりとりもお手伝いします。')],
  schema_type='AutoRepair',area_served='〇〇市'),
  hero=['car','wrench','tire'], c1='#ebe9e4', c2='#d7d3cb', stroke='#3b6ea5', ink='#5f6670', bg='#e9e7e2'),
'setsubi':dict(c=dict(slug='minato',name='みなと電気設備',short_name='みなと電気設備',kind='電気工事・水道設備｜〇〇市',
  catch_html='<span class="nw">コンセント1つから、</span><br><span class="nw">水まわりの困りごとまで。</span>',
  lead='〇〇市の電気・水道の工事店です。照明の取りかえ・エアコンの取りつけ・水もれの修理など、小さな工事からお受けしています。',
  title_place='〇〇市の電気工事・水道設備',description='〇〇市の電気・水道工事店「みなと電気設備」のホームページです（デザイン見本・架空のお店）。',
  theme_base='fresh',theme=dict(primary='#2d6b8f',primary_deep='#235670',accent='#e0a627',accent_soft='#f2d98e',pale='#e7eff4',dark='#1c2a35',dark2='#273746',bg='#f6f6f3',bg2='#ebebe5',ink='#232a30',muted='#626a71',line='#d8d8d0'),
  mark='dot',font='gothic',menu_title='お仕事の内容',menu_word='仕事',menu_lead='料金は見本です。',
  menu_note='料金は家の状態で変わります。見せていただいてからお見積もりをお出しします。',
  menus=[menu('denki','電気工事','コンセントの増設・照明の取りかえ・スイッチの修理。','3,300円〜',icon=['plug','bulb']),
         menu('suidou','水道・トイレの修理','蛇口の水もれ・トイレのつまり・給水管の取りかえ。','5,500円〜',icon=['faucet']),
         menu('aircon','エアコンの取りつけ','取りつけ・取りはずし・古いものの引き取り。','16,500円〜','1台',icon=['aircon']),
         menu('kyuto','給湯器の取りかえ','お湯が出ない・音がする、などのご相談も。',icon=['bolt','faucet'])],
  flow_title='ご依頼の流れ',flow=[dict(title='ご相談',text='困っていることをお知らせください。写真があると早いです。'),dict(title='下見',text='おうちに伺って、様子を見せていただきます。'),dict(title='お見積もり',text='内容と金額をお出しします。決めるのはそのあとで。'),dict(title='工事',text='日程を決めて工事します。終わったら一緒に確かめます。')],
  parts=dict(cases=dict(title='工事の例',eyebrow='works',lead='工事の前と後を、並べてご覧いただけます。',label_before='工事前',label_after='工事後',
                        items=[dict(before=dict(image='images/case1-before.svg',alt='工事前のトイレ（見本）',_icon=['faucet']),after=dict(image='images/case1-after.svg',alt='工事後のトイレ（見本）',_icon=['faucet','sparkle']),title='トイレの取りかえ',meta='〇〇市　個人のお宅',text='古くなったトイレを、節水型のものに取りかえました。床の張りかえも一緒に。'),
                               dict(before=dict(image='images/case2-before.svg',alt='工事前の分電盤（見本）',_icon=['bolt']),after=dict(image='images/case2-after.svg',alt='工事後の分電盤（見本）',_icon=['bolt','sparkle']),title='分電盤の取りかえ',meta='〇〇市　店舗',text='ブレーカーがよく落ちるとのことで、容量の大きいものに取りかえました。')]),
             compare=dict(title='工事の前と後',lead='つまみを動かすと、同じ場所の前と後が見比べられます。',label_before='工事前',label_after='工事後',caption='トイレの取りかえ（見本）')),
  hours='8:30〜18:00（見本）',holiday='日曜日（見本）',service_area='〇〇市とその周辺（見本）',
  reserve_title='ご相談・お見積もり',info_title='みなと電気設備について',reserve_lead='下見とお見積もりは無料です（見本）。急ぎの水もれは、まずお電話ください。',
  faq=[dict(q='急な水もれでも来てもらえますか？',a='まずお電話ください。当日に伺えないこともあります。応急の止め方もお伝えします。'),dict(q='1か所だけでも頼めますか？',a='はい、コンセント1つからお受けしています。'),dict(q='見積もりのあとで断ってもいいですか？',a='はい、大丈夫です（見本）。')],
  schema_type='HomeAndConstructionBusiness',area_served='〇〇市'),
  hero=['bolt','faucet','aircon'], c1='#e6ecf0', c2='#cfd9e0', stroke='#235670', ink='#5a6872', bg='#e7ebee'),
'estate':dict(c=dict(slug='soyokaze',name='そよかぜ不動産',short_name='そよかぜ不動産',kind='不動産｜〇〇市',
  catch_html='<span class="nw">住まいのことを、</span><br><span class="nw">近くで相談できる場所。</span>',
  lead='〇〇市の小さな不動産店です。賃貸・売買・管理・空き家のご相談まで、ひとりの担当が最後までお話をうかがいます。',
  title_place='〇〇市の不動産',description='〇〇市の不動産店「そよかぜ不動産」のホームページです（デザイン見本・架空のお店）。',
  theme_base='fresh',theme=dict(primary='#2f7a5a',primary_deep='#256247',accent='#c9a35a',accent_soft='#e6d7ac',pale='#e8f1ec',dark='#1f2d28',dark2='#2b3b35',bg='#f7f8f6',bg2='#eaeee9',ink='#242b28',muted='#626a66',line='#d6ddd7'),
  mark='dot',font='mincho',menu_title='お手伝いできること',menu_word='相談',menu_lead='どのご相談も、まずはお話から。',
  menu_note='費用は内容で変わります。先にお見積もりをお出しし、ご納得いただいてから進めます。',
  menus=[menu('chintai','賃貸','お部屋探しと、貸したい方のご相談。',icon=['key']),
         menu('baibai','売買','家・土地を買いたい方、売りたい方のご相談。',icon=['house']),
         menu('kanri','管理','貸している家・アパートの管理をお引き受けします。',icon=['building']),
         menu('akiya','空き家・相続のご相談','遠くにある実家のことなど、まずはお話をお聞かせください。',icon=['doc'])],
  flow_title='ご相談の流れ',flow=[dict(title='ご相談',text='ご希望と、いまの状況をお聞かせください。'),dict(title='ご提案',text='いくつかの方法と、かかる費用をお伝えします。'),dict(title='ご案内・下見',text='お部屋や土地を一緒に見に行きます。'),dict(title='ご契約',text='内容を一つずつ確かめてから、契約します。')],
  hours='9:30〜18:00（見本）',holiday='水曜日（見本）',parking='3台（見本）',
  info_extra=[['免許番号','〇〇県知事（0）第00000号（見本）']],
  reserve_title='ご相談・お問い合わせ',info_title='そよかぜ不動産について',reserve_lead='ご相談は無料です。LINEかお電話でどうぞ。',
  faq=[dict(q='相談だけでも大丈夫ですか？',a='はい。決めるのはあとで大丈夫です。'),dict(q='遠くにある実家のことも相談できますか？',a='はい。〇〇市とその周辺でしたら、様子を見に伺います（見本）。'),dict(q='費用はいつかかりますか？',a='契約が決まってからです。先にお見積もりをお出しします。')],
  schema_type='RealEstateAgent',area_served='〇〇市'),
  hero=['house','key','building'], c1='#e8efeb', c2='#d2dfd7', stroke='#256247', ink='#5e716a', bg='#e8eeeb'),
'farm':dict(c=dict(slug='aozora',name='あおぞら農園 直売所',short_name='あおぞら農園',kind='農家の直売所｜〇〇市',
  catch_html='<span class="nw">朝とった野菜を、</span><br><span class="nw">その日のうちに。</span>',
  lead='〇〇市の農家の直売所です。畑でとれた野菜・お米・果物と、手づくりのジャムを並べています。',
  title_place='〇〇市の農家の直売所',description='〇〇市の農家の直売所「あおぞら農園」のホームページです（デザイン見本・架空のお店）。',
  theme_base='fresh',theme=dict(primary='#5a9a3c',primary_deep='#467b2e',accent='#e8862e',accent_soft='#f6cfa5',pale='#eef5e6',dark='#26331f',dark2='#33432a',bg='#f8faf4',bg2='#edf2e4',ink='#273024',muted='#66705f',line='#d8e0cf'),
  mark='leaf',font='gothic',menu_title='並んでいるもの',menu_word='商品',menu_lead='料金は見本です。',
  menu_note='とれた分だけ並べています。時期によって、ないものもあります。',
  menus=[menu('yasai','季節の野菜','朝とったものを、その日の分だけ。','100円〜',icon=['carrot']),
         menu('kome','お米','自分の田んぼでとれたお米。精米したてをお渡しします。','2,400円','5kg',icon=['rice']),
         menu('kudamono','果物','みかん・いちごなど、時期のもの。','300円〜',icon=['apple']),
         menu('kakou','手づくりの加工品','畑の果物で作ったジャム・ピクルス。','500円〜',icon=['jar'])],
  hours='9:00〜15:00（見本）',holiday='月〜水曜日（見本）',parking='8台（見本）',payment='現金のみ（見本）',
  info_extra=[['入荷のお知らせ','LINEでお知らせしています（見本）']],
  reserve_title='お取り置き・お問い合わせ',info_title='直売所のこと',reserve_lead='お米のまとめ買い・野菜のお取り置きは、LINEかお電話でどうぞ。',
  faq=[dict(q='何が並んでいますか？',a='その日の朝にとれたものです。LINEでお知らせしています（見本）。'),dict(q='取り置きはできますか？',a='はい。前日までにお知らせください（見本）。'),dict(q='発送はできますか？',a='いまは店頭でのお渡しだけです（見本）。')],
  schema_type='Store',area_served='〇〇市'),
  hero=['carrot','rice','apple'], c1='#ecf2e3', c2='#d8e4c9', stroke='#467b2e', ink='#5f7352', bg='#ebf0e3'),
'trimming':dict(c=dict(slug='tekuteku',name='トリミングサロン てくてく',short_name='てくてく',kind='ペットのトリミング｜〇〇市',
  catch_html='<span class="nw">その子のペースで、</span><br><span class="nw">きれいに、やさしく。</span>',
  lead='〇〇市のトリミングサロンです。1頭ずつ、ゆっくり時間をとって。はじめての子も、年をとった子も。',
  title_place='〇〇市のペットのトリミング',description='〇〇市のトリミングサロン「てくてく」のホームページです（デザイン見本・架空のお店）。',
  theme_base='salon',theme=dict(primary='#e07b4a',primary_deep='#bf6235',accent='#7fa88a',accent_soft='#cfe0d2',pale='#fbeee6',dark='#2f2a26',dark2='#3d3732',bg='#fbf8f4',bg2='#f2ece4',ink='#33302b',muted='#75706a',line='#e6ddd2'),
  mark='heart',font='gothic',menu_title='メニュー・料金',menu_word='メニュー',menu_lead='料金は見本です。',
  menu_note='犬種・大きさ・毛の状態で変わります。',
  menus=[menu('shampoo','シャンプーコース','シャンプー・爪切り・耳そうじ・足まわりのカット。','3,300円〜','小型犬',icon=['bath']),
         menu('cut','カットコース','シャンプーコースに、全身のカット。','5,500円〜','小型犬',icon=['scissors','dog']),
         menu('part','部分ケア','爪切り・耳そうじ・肛門腺だけ、でも大丈夫。','550円〜',icon=['paw']),
         menu('sougei','送迎','〇〇市内は、お迎えとお送りをしています。','片道 550円',icon=['car','paw'])],
  hours='9:00〜18:00（見本）',holiday='木曜日（見本）',parking='2台（見本）',payment='現金・QRコード決済（見本）',
  reserve_title='ご予約',info_title='お店のこと',reserve_lead='ご予約はLINEかお電話で。はじめての子は、ワクチンの証明書をお持ちください（見本）。',
  faq=[dict(q='大型犬もお願いできますか？',a='はい。大きさによって料金と時間が変わります。ご予約のときにお知らせください。'),dict(q='猫もできますか？',a='いまは犬だけお受けしています（見本）。'),dict(q='こわがりの子でも大丈夫ですか？',a='はい。休みながら、その子のペースで進めます。')],
  schema_type='LocalBusiness',area_served='〇〇市'),
  hero=['dog','paw','scissors'], c1='#f4e9df', c2='#e6d4c3', stroke='#bf6235', ink='#8a7366', bg='#f2e8de'),
'studio':dict(c=dict(slug='hikarido',name='写真館 ひかり堂',short_name='ひかり堂',kind='写真館｜〇〇市',
  catch_html='<span class="nw">その日の顔を、</span><br><span class="nw">ずっと残せるように。</span>',
  lead='〇〇市の写真館です。七五三・成人式・家族写真・証明写真。緊張しない、ゆっくりした撮影を心がけています。',
  title_place='〇〇市の写真館',description='〇〇市の写真館「ひかり堂」のホームページです（デザイン見本・架空のお店）。',
  theme_base='salon',theme=dict(primary='#9a7b4f',primary_deep='#7d6239',accent='#c9b07a',accent_soft='#e6d9b8',pale='#f4efe6',dark='#1f1d1b',dark2='#2c2927',bg='#f7f5f1',bg2='#ece8e1',ink='#2a2724',muted='#6f6a63',line='#ddd6ca'),
  mark='dot',font='mincho',menu_title='撮影メニュー・料金',menu_word='撮影',menu_lead='料金は見本です。',
  menu_note='写真のデータと、台紙や額はメニューによって変わります。くわしくはお問い合わせください。',
  menus=[menu('753','七五三','着物の着付けとヘアセット込み。','22,000円〜',icon=['camera','star']),
         menu('seijin','成人式・卒業','前撮り・後撮り、どちらも。','16,500円〜',icon=['frame']),
         menu('family','家族写真','お宮参り・入学・記念日に。ペットも一緒にどうぞ。','11,000円〜',icon=['frame','camera']),
         menu('shoumei','証明写真','履歴書・パスポート・受験用。その場でお渡しします。','1,650円',icon=['camera'])],
  hours='10:00〜18:00（見本）',holiday='火曜日（見本）',parking='4台（見本）',payment='現金・クレジットカード（見本）',
  reserve_title='ご予約',info_title='写真館のこと',reserve_lead='撮影はご予約制です（証明写真はご予約なしでどうぞ）。衣装のご相談もお気軽に。',
  faq=[dict(q='写真のデータはもらえますか？',a='はい。撮影メニューにデータが付いています（見本）。'),dict(q='衣装の持ち込みはできますか？',a='はい。お持ちの着物・服でも撮影できます。'),dict(q='撮影はどのくらい時間がかかりますか？',a='七五三で、着付けを入れて2時間ほどです（見本）。')],
  schema_type='LocalBusiness',area_served='〇〇市'),
  hero=['camera','frame','sparkle'], c1='#ece6dc', c2='#dbd1c0', stroke='#7d6239', ink='#776b5c', bg='#ebe6dd'),
}
BEFORE=('#d8d2c6','#b9b1a3','#8a847a','#7a746a')  # 部品の「前」の写真（灰色っぽく）
MIHON_CSS='''
/* 見本帳にもどる（見本だけに出す） */
.mihon{position:fixed;left:50%;-webkit-transform:translateX(-50%);transform:translateX(-50%);bottom:16px;z-index:200;background:rgba(25,25,25,.85);color:#fff !important;font:500 12px/1.4 "Hiragino Sans","Noto Sans CJK JP",sans-serif;letter-spacing:.06em;padding:.7em 1.3em;border-radius:999px;text-decoration:none;white-space:nowrap;box-shadow:0 4px 14px rgba(0,0,0,.2)}
.mihon:hover{background:#000}
@media (max-width:860px){.mihon{bottom:78px}}
'''
only=sys.argv[2].split(',') if len(sys.argv)>2 else list(SAMPLES)
for d in only:
    spec=SAMPLES[d]; c=dict(COMMON); c.update(spec['c'])
    out=f'{ROOT}/samples/{d}'
    for m in c['menus']:
        icons=m.pop('_icon')
        svg(f'{out}/{m["image"]}',1000,750,icons,m['name']+'の写真が入ります',spec['c1'],spec['c2'],spec['stroke'],spec['ink'])
    # 部品（施工例・前と後）の写真。「前」は灰色っぽく、「後」はお店の色で（仮画像でも見比べが分かるように）
    cs=(c.get('parts') or {}).get('cases') or {}
    for it in cs.get('items',[]):
        for key in ('before','after'):
            o=it[key]; icons=o.pop('_icon',['tools'])
            col=BEFORE if key=='before' else (spec['c1'],spec['c2'],spec['stroke'],spec['ink'])
            svg(f'{out}/{o["image"]}',1000,750,icons,cs.get('label_'+key,'')+'の写真が入ります',*col)
    c['hero']=dict(image='images/hero.svg',w=1200,h=1500,alt='お店の写真')
    t=c['theme']; svg(f'{out}/images/hero.svg',1200,1500,spec['hero'],'お店の写真が入ります',t['dark2'],t['dark'],t['accent_soft'],'rgba(255,255,255,.55)')
    c['_説明']='デザイン見本（架空のお店）。make_site.py で作った'
    cf=f'{S}/{d}.json'; json.dump(c,open(cf,'w'),ensure_ascii=False,indent=1)
    subprocess.run([sys.executable,f'{ROOT}/tools/make_site.py',cf,out],stdout=subprocess.DEVNULL)
    p=f'{out}/index.html'; s=open(p,encoding='utf-8').read()
    s=re.sub(r'href="(#[^"]*)" target="_blank" rel="noopener"', r'href="\1"', s)
    s=s.replace('<title>','<title>【見本】',1)
    s=s.replace('</style>',MIHON_CSS+'</style>',1)
    s=s.replace('</body>','<a class="mihon" href="../index.html">デザイン見本（架空のお店）｜見本帳にもどる</a>\n</body>',1)
    open(p,'w',encoding='utf-8').write(s)
    for f in ('index.old.html',):
        if os.path.exists(f'{out}/{f}'): os.remove(f'{out}/{f}')
    print('ok',d)
